server:
  port: 8080


#JDBC 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csumall?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


#日志记录
logging:
  level:
    org.csu.csumall.mapper: debug

# mybatis-plus配置
mybatis-plus:
#  mapper-locatios:
  global-config:
    db-config:
      # 表名前缀
      table-prefix: csumall_
      # 主键策略，自增，数据库中需要设置主键自增
      id-type: auto
  # 配置实体类包地址
  type-aliases-package: org.csu.csumall.entity